language: java
install:
- "./gradlew -b gradle/bootstrap.gradle bootstrap"
script:
- git describe --tags > VERSION.txt
- rm -rf .gradle gradle/.gradle .git
- zip -r sap-dtr-git-bridge.zip .
deploy:
  provider: releases
  api_key:
    secure: "e92q2agFj9X1LaTODPfTVETAcY6M+6i+HY6qxqQoSoQFGC+G8WyjbM0/pmTXBr2FLrLjJmpt0GhKKywwkwQKUVPonPZGU/yCmoOEUgYhhFyIDN0zOuORr1fkvD3f0BJGrGaAUo1Op93M39wSdT54DgkExS3GO7IFb3IM+xvQWAo/PKKfhvkqF10SPf7+xqs1eBjO72UCOqcaFVW/UeTst5QjVwNmojxKuuWewwiERhOwM0v7LPgVuh0Un6tqjhVQZAUSP0WLNxmXCwxVaeWW46u38nZ5V42r8ZjlDZMe2zxORFlXWx7rdPfhbJ/rWIVaya43ikAN++DKS2wUT7qnS9CiLQXABWJmIOSSXvj4wHIaIPZDieIqAlBq/OPRy3W1tPcXtuPF2wx55QMN0TsnHGtkHz3v5tuj6IJxewDmS519iFX1KpKTKpYXWwIPlcg6KLQZ/onjTp2n/CZ1plZ2sTtuDspbe607bmynHcHNDKwbkvOmjyFG1qaiz5ss3+EbR/yppWVT9EnGNVYWzHFVNMozlY6iw88EYKNhott68kJ4eAOLjYRAhnhVER/sTmTIhzWpAojDzwPGXoBmtROlc22oebmVvMGv+P0Vm8B4RjEgIFuQySlK5uRwzcVYEIbtqKhN1RGYkvjwLgA5YlevH0CEFg8N83FTKOQzkG8vF1c="
  skip_cleanup: true
  file: sap-dtr-git-bridge.zip
  on:
    repo: agoeb/sap-dtr-git-bridge
    tags: true

